#!/usr/bin/env bash
# Phase 3 Tier 2 — emit mlnd env files for a Tor + public LitVM (chain 4441) lab.
#
# Reads deploy/litvm-addresses.generated.env for REGISTRY + COURT + CHAIN_ID.
# Writes deploy/tier2.maker{1,2,3}.env with per-maker operator key, nostr nsec, Tor .onion URL.
#
# Inputs (env):
#   TIER2_RELAY_WS     wss:// URL of curated relay (required; see research/PHASE_3_TIER2_RELAY.md)
#   TIER2_LITVM_WS     wss:// LitVM WebSocket JSON-RPC (default wss://liteforge.rpc.caldera.xyz/ws)
#   TIER2_LITVM_HTTP   https:// LitVM HTTP JSON-RPC (default https://liteforge.rpc.caldera.xyz/http)
#   TIER2_MAKERi_PK      (i=1..3) 0x-prefixed 64-hex LitVM operator private key (required)
#   TIER2_MAKERi_NSEC    (i=1..3) nsec1… or 64-hex Nostr secret (required)
#   TIER2_MAKERi_ONION   (i=1..3) full http://<56char>.onion:PORT (required)
#   TIER2_MAKERi_SWAP_X25519_PUB_HEX (i=1..3) 64-hex X25519 pub key (optional; recommended for pathfind)
#   TIER2_NOSTR_AUTH   set to 1 to enable NIP-42 AUTH on the broadcaster (MLND_NOSTR_AUTH=true)
#
# Usage:
#   TIER2_RELAY_WS=wss://your-relay.example/ \
#     TIER2_MAKER1_PK=0x... TIER2_MAKER1_NSEC=... TIER2_MAKER1_ONION=http://abc.onion:8334 \
#     TIER2_MAKER2_PK=0x... TIER2_MAKER2_NSEC=... TIER2_MAKER2_ONION=http://def.onion:8335 \
#     TIER2_MAKER3_PK=0x... TIER2_MAKER3_NSEC=... TIER2_MAKER3_ONION=http://ghi.onion:8336 \
#     ./scripts/phase3-tier2-setup.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEPLOY="$ROOT/deploy"
ADDRS_ENV="$DEPLOY/litvm-addresses.generated.env"

if [[ ! -f "$ADDRS_ENV" ]]; then
  echo "error: $ADDRS_ENV not found — run 'make broadcast-litvm && make record-litvm-deploy' first" >&2
  exit 1
fi

# shellcheck disable=SC1090
set -a; . "$ADDRS_ENV"; set +a

: "${MLND_LITVM_CHAIN_ID:?missing in $ADDRS_ENV}"
: "${MLND_REGISTRY_ADDR:?missing in $ADDRS_ENV}"
: "${MLND_COURT_ADDR:?missing in $ADDRS_ENV}"

: "${TIER2_RELAY_WS:?required: wss:// URL of curated relay (see research/PHASE_3_TIER2_RELAY.md)}"
TIER2_LITVM_WS="${TIER2_LITVM_WS:-wss://liteforge.rpc.caldera.xyz/ws}"
TIER2_LITVM_HTTP="${TIER2_LITVM_HTTP:-https://liteforge.rpc.caldera.xyz/http}"
TIER2_NOSTR_AUTH="${TIER2_NOSTR_AUTH:-0}"

require_set() {
  local name="$1"
  if [[ -z "${!name:-}" ]]; then
    echo "error: $name is required" >&2; exit 1
  fi
}

derive_addr() {
  # Best-effort derivation via docker cast; writes 0x-prefixed checksum.
  local pk="$1"
  if command -v cast >/dev/null 2>&1; then
    cast wallet address --private-key "$pk"
  else
    docker run --rm --entrypoint cast ghcr.io/foundry-rs/foundry:latest wallet address --private-key "$pk" 2>/dev/null | tr -d '[:space:]'
  fi
}

write_maker() {
  local i="$1"
  local pk_var="TIER2_MAKER${i}_PK"
  local nsec_var="TIER2_MAKER${i}_NSEC"
  local onion_var="TIER2_MAKER${i}_ONION"
  local swap_var="TIER2_MAKER${i}_SWAP_X25519_PUB_HEX"

  require_set "$pk_var"; require_set "$nsec_var"; require_set "$onion_var"

  local pk="${!pk_var}"
  local nsec="${!nsec_var}"
  local onion="${!onion_var}"
  local swap_pub="${!swap_var:-}"

  local addr
  addr="$(derive_addr "$pk")"
  if [[ -z "$addr" ]]; then
    echo "error: could not derive EVM address for maker $i (install foundry cast or ensure docker is running)" >&2
    exit 1
  fi
  local addr_lc
  addr_lc="$(echo "$addr" | tr '[:upper:]' '[:lower:]')"

  local out="$DEPLOY/tier2.maker${i}.env"
  {
    echo "# Tier 2 maker $i — LitVM chain $MLND_LITVM_CHAIN_ID (public testnet), curated relay, Tor HS."
    echo "# Generated by scripts/phase3-tier2-setup.sh. chmod 600 before handing to an operator."
    echo "MLND_WS_URL=$TIER2_LITVM_WS"
    echo "MLND_HTTP_URL=$TIER2_LITVM_HTTP"
    echo "MLND_LITVM_CHAIN_ID=$MLND_LITVM_CHAIN_ID"
    echo "MLND_REGISTRY_ADDR=$MLND_REGISTRY_ADDR"
    echo "MLND_COURT_ADDR=$MLND_COURT_ADDR"
    echo "MLND_OPERATOR_ADDR=$addr_lc"
    echo "MLND_OPERATOR_PRIVATE_KEY=$pk"
    echo "MLND_NOSTR_RELAYS=$TIER2_RELAY_WS"
    echo "MLND_NOSTR_NSEC=$nsec"
    echo "MLND_NOSTR_INTERVAL=30m"
    if [[ "$TIER2_NOSTR_AUTH" == "1" || "$TIER2_NOSTR_AUTH" == "true" ]]; then
      echo "MLND_NOSTR_AUTH=true"
    fi
    echo "MLND_TOR_ONION=$onion"
    echo "MLND_DB_PATH=/data/mlnd.db"
    echo "MLND_FEE_MIN_SAT=1"
    echo "MLND_FEE_MAX_SAT=100"
    if [[ -n "$swap_pub" ]]; then
      echo "MLND_SWAP_X25519_PUB_HEX=$swap_pub"
    fi
  } >"$out"
  chmod 600 "$out"
  echo "wrote $out (operator $addr_lc, onion $onion)"
}

mkdir -p "$DEPLOY"
write_maker 1
write_maker 2
write_maker 3

TAKER_ENV="$DEPLOY/tier2.taker.env"
cat >"$TAKER_ENV" <<EOF
# Tier 2 taker — point mln-cli scout/pathfind/forger at public LitVM (chain $MLND_LITVM_CHAIN_ID).
# See research/PHASE_3_OPERATOR_PARTB_STEPBYSTEP.md sections 4–9.
export MLN_NOSTR_RELAYS=$TIER2_RELAY_WS
export MLN_LITVM_HTTP_URL=$TIER2_LITVM_HTTP
export MLN_LITVM_CHAIN_ID=$MLND_LITVM_CHAIN_ID
export MLN_REGISTRY_ADDR=$MLND_REGISTRY_ADDR
export MLN_GRIEVANCE_COURT_ADDR=$MLND_COURT_ADDR
EOF
chmod 600 "$TAKER_ENV"
echo "wrote $TAKER_ENV"

cat <<EOF

Next:
  1) Each maker host: copy tier2.maker{1,2,3}.env (chmod 600), 'make maker onboard' with TIER2_MAKERi_PK,
     start mlnd with --env-file, then start coinswapd-research behind a Tor hidden service
     (HiddenServicePort matching the port in MLND_TOR_ONION).
  2) Taker host: source deploy/tier2.taker.env; make phase3-operator-preflight; make build-mln-cli;
     ./bin/mln-cli doctor  (expect verified>=3, all with tor)
     ./bin/mln-cli route build -out route.json
  3) Tier 3 funded swap: see research/PHASE_3_OPERATOR_CHECKLIST.md section D and
     make phase3-funded-preflight.
EOF
