#!/usr/bin/env python3
"""Extract MwixnetRegistry + GrievanceCourt addresses and chain id from a Foundry broadcast JSON.

Used after `forge script ... --broadcast` to wire `deploy/.env.testnet` and taker CLI env.
See PHASE_16_PUBLIC_TESTNET.md and deploy/.env.testnet.example.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def _find_latest_broadcast(root: Path) -> Path | None:
    base = root / "contracts" / "broadcast" / "Deploy.s.sol"
    if not base.is_dir():
        return None
    candidates = list(base.glob("*/run-latest.json"))
    if not candidates:
        return None
    return max(candidates, key=lambda p: p.stat().st_mtime)


def _parse_addresses(data: dict) -> tuple[str, str]:
    reg, court = None, None
    for t in data.get("transactions", []):
        if t.get("transactionType") != "CREATE":
            continue
        cn = t.get("contractName")
        if cn == "MwixnetRegistry":
            reg = t.get("contractAddress")
        elif cn == "GrievanceCourt":
            court = t.get("contractAddress")
    if not reg or not court:
        raise ValueError("broadcast missing MwixnetRegistry or GrievanceCourt CREATE transaction")
    return reg.lower(), court.lower()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--broadcast-json",
        type=Path,
        help="Path to run-latest.json (default: newest under contracts/broadcast/Deploy.s.sol/)",
    )
    ap.add_argument(
        "--write",
        type=Path,
        metavar="FILE",
        help="Write env fragment to FILE (default: print to stdout)",
    )
    args = ap.parse_args()

    root = Path(__file__).resolve().parent.parent
    bpath = args.broadcast_json
    if bpath is None:
        bpath = _find_latest_broadcast(root)
        if bpath is None:
            print(
                "No broadcast JSON found. Deploy first:\n"
                "  ./scripts/broadcast-litvm-testnet.sh\n"
                "or pass --broadcast-json contracts/broadcast/Deploy.s.sol/<chainId>/run-latest.json",
                file=sys.stderr,
            )
            return 1

    data = json.loads(bpath.read_text(encoding="utf-8"))
    chain = data.get("chain")
    if chain is None:
        print("broadcast JSON missing top-level 'chain'", file=sys.stderr)
        return 1
    chain_str = str(int(chain))

    try:
        reg, court = _parse_addresses(data)
    except ValueError as e:
        print(e, file=sys.stderr)
        return 1

    try:
        src_label = str(bpath.relative_to(root))
    except ValueError:
        src_label = str(bpath.resolve())

    lines = [
        f"# Generated by scripts/record-litvm-deploy.py from {src_label}",
        "# Merge into deploy/.env.testnet (see deploy/.env.testnet.example). Do not commit.",
        "",
        f"MLND_LITVM_CHAIN_ID={chain_str}",
        f"MLND_REGISTRY_ADDR={reg}",
        f"MLND_COURT_ADDR={court}",
        "",
        "# Taker: mln-cli / Wails — set HTTP RPC from LitVM docs (same chain as WS above)",
        f"# export MLN_LITVM_CHAIN_ID={chain_str}",
        "# export MLN_LITVM_HTTP_URL=https://REPLACE_HTTP_JSON_RPC",
        f"# export MLN_REGISTRY_ADDR={reg}",
        f"# export MLN_GRIEVANCE_COURT_ADDR={court}",
        "",
        "# Nostr: mlnd publishes kind 31250 with litvm.registry / litvm.grievanceCourt from these env vars.",
        "# After changing addresses, restart mlnd so maker ads match the new deployment.",
        "",
    ]
    text = "\n".join(lines)

    if args.write:
        args.write.parent.mkdir(parents=True, exist_ok=True)
        args.write.write_text(text, encoding="utf-8")
        print(f"Wrote {args.write}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
